import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
    padding: 0,
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  logoContainer: {
    position: 'relative',
    marginTop: 200,
    paddingTop: 60,
    paddingBottom: 80,
    paddingHorizontal: 20,
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  logoText: {
    marginTop: -55,
    textAlign: 'center',
    color: '#0f4248',
    fontSize: 55,
    fontWeight: '700',
    zIndex: 1,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 70,
    paddingHorizontal: 20,
    paddingVertical: 30,
  },
  loginButton: {
    backgroundColor: '#528d94',
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signupButton: {
    backgroundColor: '#0f4248',
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  bottomBox: {
    backgroundColor: 'rgba(15, 30, 46, 0.7)',
    height: '43%',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    margin: 0,
    padding: 30,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  boxIcon: {
    width: 300,
    height: 300,
    position: 'absolute',
    top: 0,
    zIndex: 2,
  },
  boxWelcomeText: {
    fontSize: 35,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center',
  },
  boxDescriptionText: {
    fontSize: 15,
    color: '#ffffff',
    textAlign: 'center',
    lineHeight: 25,
    opacity: 0.85,
    paddingTop: 10,
  },
});
